package com.alodiga.wallet.respuestas;

public enum ResponseCode {

    EXITO("00"),
    DATOS_INVALIDOS("01"),
    CONTRASENIA_EXPIRADA("03"),
    IP_NO_CONFIANZA("04"),
    CREDENCIALES_INVALIDAS("05"),
    USUARIO_BLOQUEADO("06"),
    CODIGO_VALIDACION_INVALIDO("07"),
    NUMERO_TELEFONO_YA_EXISTE("08"),
    ENVIO_CORREO_FALLIDO("09"),
    CORREO_YA_EXISTE("10"),
    DATOS_NULOS("11"),
    PRIMER_INGRESO("12"),
    EIN_YA_EXISTE("14"),
    FEDERAL_TAX_YA_EXISTE("15"),
    CUENTA_BANCARIA_YA_EXISTE("17"),
    GENERAR_CODIGO("18"),
    TOKEN_EXPIRADO("19"),
    SOLICITUD_TARJETA_ACTIVA("20"),
    AFILIACIONES_MAXIMAS_ALCANZADAS("21"),
    USER_NOT_HAS_PHONE_NUMBER("22"),
    USER_NOT_HAS_PRODUCT("23"),
    TRANSACTION_LIST_NOT_FOUND_EXCEPTION("24"),
    EMPTY_LIST_HAS_BANK("25"),
    EMPTY_LIST_COUNTRY("26"),
    BALANCE_HISTORY_NOT_FOUND_EXCEPTION("27"),
    EMPTY_LIST_HAS_CARD("28"),
    USER_NOT_HAS_CARD("29"),
    DOES_NOT_HAVE_AN_ASSOCIATED_COMPANION_CARD("30"),
    APLICACION_NO_EXISTE("94"),
    USUARIO_SOSPECHOSO("95"),
    USUARIO_PENDIENTE("96"),
    USUARIO_NO_EXISTE("97"),
    ERROR_CREDENCIALES("98"),
    ERROR_INTERNO("99"),
    //Mensajeria TopUp
    DENOMINATION_NOT_AVAILABLE("301"),
    DESTINATION_MSISDN_OUT_OF_RANGE("101"),
    DESTINATION_NOT_PREPAID("204"),
    ERROR_TRANSACTION_TOP_UP("205"),
    //Mensajes Guardar Transaction
    TRANSACTION_AMOUNT_LIMIT("30"),
    TRANSACTION_MAX_NUMBER_BY_ACCOUNT("31"),
    TRANSACTION_MAX_NUMBER_BY_CUSTOMER("32"),
    USER_HAS_NOT_BALANCE("33"),
    //Mensajes Status Cumplimient
    NOT_VALIDATE("40"),
    //Mensajes Status Card
    CARD_NUMBER_EXISTS("50"),
    NOT_ALLOWED_TO_CHANGE_STATE("51"),
    THERE_IS_NO_SEARCH_RECORD("52"),
    NON_EXISTENT_ACCOUNT("53"),
    AUTHENTICATE_IMPOSSIBLE("54"),
    SERVICE_NOT_ALLOWED("55"),
    OPERATION_NOT_ALLOWED_FOR_THIS_SERVICE("56"),
    UNABLE_TO_ACCESS_DATA("57"),
    THERE_ARE_NO_RECORDS_FOR_THE_REQUESTED_SEARCH("58"),
    THE_REQUESTED_PRODUCT_DOES_NOT_EXIST("59"),
    THE_NUMBER_OF_ORDERS_ALLOWED_IS_EXCEEDED("60"),
    
    //Mensajes transferencia cardtocard credencial servicio autorizacion
    NON_EXISTENT_CARD("100"),
    
    EXPIRATION_DATE_DIFFERS("102"),
    EXPIRED_CARD("103"),
    LOCKED_CARD("104"),
    BLOCKED_ACCOUNT("105"),
    INVALID_ACCOUNT("106"),
    INSUFFICIENT_BALANCE("107"),
    INSUFFICIENT_LIMIT("108"),
    CREDIT_LIMIT_0("109"),
    CREDIT_LIMIT_0_OF_THE_DESTINATION_ACCOUNT("110"),
    ERROR_PROCESSING_THE_TRANSACTION("111"),
    INVALID_TRANSACTION("112"),
    ERROR_VALIDATION_THE_TERMINAL("113"),
    DESTINATION_CARD_LOCKED("114"),    
    DESTINATION_ACCOUNT_LOCKED("115"),
    INVALID_DESTINATION_CARD("116"),
    INVALID_DESTINATION_ACCOUNT("117"),
    THE_AMOUNT_MUST_BE_POSITIVE_AND_THE_AMOUNT_IS_REPORTED("118"),
    THE_AMOUNT_MUST_BE_NEGATIVE_AND_THE_AMOUNT_IS_REPORTED("119"),
    INVALID_TRANSACTION_DATE("120"),
    INVALID_TRANSACTION_TIME("121"),
    SOURCE_OR_DESTINATION_ACCOUNT_IS_NOT_COMPATIBLE_WITH_THIS_OPERATION_NN("122"),
    SOURCE_OR_DESTINATION_ACCOUNT_IS_NOT_COMPATIBLE_WITH_THIS_OPERATION_SN("123"),
    SOURCE_OR_DESTINATION_ACCOUNT_IS_NOT_COMPATIBLE_WITH_THIS_OPERATION_NS("124"),
    TRASACTION_BETWEEN_ACCOUNTS_NOT_ALLOWED("125"),
    TRADE_VALIDATON_ERROR("126"),
    DESTINATION_CARD_DOES_NOT_SUPPORT_TRANSACTION("127"),
    OPERATION_NOT_ENABLED_FOR_THE_DESTINATION_CARD("128"),
    BIN_NOT_ALLOWED("129"),
    STOCK_CARD("130"),
    THE_ACCOUNT_EXCEEDS_THE_MONTHLY_LIMIT("131"),
    THE_PAN_FIELD_IS_MANDATORY("132"),
    THE_AMOUNT_TO_BE_RECHARGE_IS_INCORRECT("133"),
    THE_AMOUNT_MUST_BE_GREATER_THAN_0("134"),
    TRANSACTION_ANSWERED("135"),
    SUCCESSFUL_RECHARGE("136"),
    ERROR_VALIDATING_PIN("137"),
    ERROR_VALIDATING_CVC1("138"),
    ERROR_VALIDATING_CVC2("139"),
    PIN_CHANGE_ERROR("140"),
    ERROR_VALIDATING_THE_ITEM("141"),
    INVALID_AMOUNT("142");
   

    private String codigo; 
	

private ResponseCode(String codigo){
		this.codigo = codigo;
	}
	
	public String getCodigo(){
		return codigo;
	}

}
